### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by johnmcguin** [angusjf/elm-astro-integration#3]
Hey there 👋 , would you mind versioning and publishing the latest changes to the dev server? I am still not seeing this on NPM yet and hoping that it can land there so we can use the package.

#2 & #1

**Comment by angusjf** [comment]
SORRY bear with me took me forever to get back into my npm account

published here: https://www.npmjs.com/package/astro-integration-elm/v/0.0.10

let me know if you would be interested in me transferring ownership of this project

**Comment by johnmcguin** [comment]
I ended up going with another astro integration for my project, so I don't really have a use case for this at the moment. I don't think I would be a good maintainer without being a user. I could try to find some time to help contribute to this though. I could try to make a PR to publish to npm with your help, just to get that set up for future PRs. Let me know what you think

**Comment by johnmcguin** [comment]
TY!
